### ISSUE TITLE
Add "Arrays" variable

### ISSUE THREAD

**Issue by Sarfraz-droid** [Sarfraz-droid/fflow#3]
Currently the pre-defined variables are only limited to string bool and number. 

Add arrays UI and implementation for the input

**Comment by SattyamSamania** [comment]
Hey @Sarfraz-droid can you assign this issue to me under KWOC and also tell me further what to do next.

**Comment by Sarfraz-droid** [comment]
@SattyamSamania Sorry I'll be a bit busy due to work, etc. So JS-Blueprints will not be participating in KWOC

**Comment by SattyamSamania** [comment]
No worries. Thanks for the reply.
